services:
  neo4j:
    image: neo4j:5.26.0-enterprise
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_AUTH: neo4j/testpass
      NEO4J_dbms_mode: SINGLE
      NEO4J_dbms_connector_bolt_tls__level: DISABLED
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/import
      - ./plugins:/plugins
    restart: unless-stopped
