version: '3.8'

services:
  neo4j:
    image: neo4j:5.26.0-enterprise
    container_name: neo4j
    ports:
      - 7474:7474  # Browser
      - 7687:7687  # Bolt
    environment:
      NEO4J_AUTH: neo4j/testpass
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_default__database: neo4j
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/import
      - ./plugins:/plugins
